// <auto-generated />
using System;
using DesafioToLife.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioToLife.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128202137_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioToLife.Domain.Entities.Aparelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Aparelhos", (string)null);
                });

            modelBuilder.Entity("DesafioToLife.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AparelhoId")
                        .HasColumnType("int");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("PhonePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhonePriceOnPlan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AparelhoId");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("DesafioToLife.Domain.Entities.Plano", b =>
                {
                    b.HasOne("DesafioToLife.Domain.Entities.Aparelho", null)
                        .WithMany("Planos")
                        .HasForeignKey("AparelhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DesafioToLife.Domain.ValueObjects.Localidade", "Localidade", b1 =>
                        {
                            b1.Property<int>("PlanoId")
                                .HasColumnType("int");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NomeLocalidade");

                            b1.Property<int>("Prioridade")
                                .HasColumnType("int")
                                .HasColumnName("PrioridadeLocalidade");

                            b1.HasKey("PlanoId");

                            b1.ToTable("Planos");

                            b1.WithOwner()
                                .HasForeignKey("PlanoId");
                        });

                    b.OwnsOne("DesafioToLife.Domain.ValueObjects.Schedule", "Schedule", b1 =>
                        {
                            b1.Property<int>("PlanoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDateSchedule");

                            b1.HasKey("PlanoId");

                            b1.ToTable("Planos");

                            b1.WithOwner()
                                .HasForeignKey("PlanoId");
                        });

                    b.Navigation("Localidade")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("DesafioToLife.Domain.Entities.Aparelho", b =>
                {
                    b.Navigation("Planos");
                });
#pragma warning restore 612, 618
        }
    }
}
